server:
  port: 8081


spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.blog.frontend.module.*.entity
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true

---
spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.131.133:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: blog_frontend
    password: n3MJLtZg^XA@SxmO
    # Hikari 连接池配置
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      pool-name: BlogFrontendCP
      max-lifetime: 1800000
      connection-timeout: 30000
  # devtools 相关
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true

swagger:
  enable: true

---

