server:
  port: 8081

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: blog_frontend
    password: qe9aKUiJrCH68EGZ
    # Hikari 连接池配置
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      pool-name: BlogFrontendCP
      max-lifetime: 1800000
      connection-timeout: 30000
swagger:
  enable: true
---

